codegen: tc: update header offset when pushing fixed headers
The tc-prio example is currently failing with the following error.

  $ cargo run --example tc-prio ens5

    thread 'main' (470526) panicked at netlink-socket/examples/tc-prio.rs:32:9:
    internal error: entered unreachable code: Err(
       Invalid argument (os error 22): bytes leftover after parsing attributes,
    )

This is due to wrong update of the header offset when pushing fixed
headers in PushAttrs implementation. This leads to uninitialized
nested header.

Example code diff.

@@ -26500,7 +26500,7 @@ impl<Prev: Rec> PushAttrs<Prev> {

     [...]

     #[doc = "At most one sub-message attribute is expected per attribute set."]
     pub fn nested_options_prio(mut self, fixed_header: &PushTcPrioQopt) -> Self {
         self = self.push_kind(c"prio");
-        push_nested_header(self.as_rec_mut(), 2u16);
+        self.header_offset = Some(push_nested_header(self.as_rec_mut(), 2u16));
         self.as_rec_mut().extend(fixed_header.as_slice());
         self
     }

    [...]